FROM node:lts-bullseye-slim
WORKDIR /home/app

COPY . .
RUN node --version # optional to check that it worked
RUN npm --version # optional to check that it worked
RUN npm install -g npm@latest
RUN npm --version # check new version npm

USER node

RUN npm install

COPY --chown=node:node . .

EXPOSE $SERVER_PORT

CMD ["node", "app.js"]
